services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /media/max/Expansion/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./media:/app/media
      - ./easyocr_models:/app/easyocr_models
      - ./ocr_metrics:/app/ocr_metrics
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"