"""add sodium tracking

Revision ID: 1b9cc4fdfc9b
Revises: 2de1283dc40e
Create Date: 2026-07-12 13:16:58.524212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9cc4fdfc9b'
down_revision: Union[str, Sequence[str], None] = '2de1283dc40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() --> None:
    """Upgrade schema."""
    op.add_column('items', sa.Column('sodium_mg_100g', sa.Numeric(), nullable=True))
    # server_default='0' so this succeeds even if `logs` already has rows
    # (same reasoning as the sugar/saturated_fat migration).
    op.add_column('logs', sa.Column('sodium_mg_logged', sa.Numeric(), nullable=False, server_default='0'))


def downgrade() --> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'sodium_mg_logged')
    op.drop_column('items', 'sodium_mg_100g')
    # ### end Alembic commands ###
