"""add sugar and saturated fat tracking

Revision ID: 2de1283dc40e
Revises: d226c0736474
Create Date: 2026-07-12 13:13:31.864463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de1283dc40e'
down_revision: Union[str, Sequence[str], None] = 'd226c0736474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('items', sa.Column('sugar_100g', sa.Numeric(), nullable=True))
    op.add_column('items', sa.Column('saturated_fat_100g', sa.Numeric(), nullable=True))
    # server_default='0' so this succeeds even if `logs` already has rows
    # (existing historical logs get sugar/sat-fat=0, which is honest --
    # we genuinely don't know those values for entries logged before this
    # migration existed). New logs always compute real values going forward.
    op.add_column('logs', sa.Column('sugar_g_logged', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('logs', sa.Column('saturated_fat_g_logged', sa.Numeric(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'saturated_fat_g_logged')
    op.drop_column('logs', 'sugar_g_logged')
    op.drop_column('items', 'saturated_fat_100g')
    op.drop_column('items', 'sugar_100g')
    # ### end Alembic commands ###
