"""add goal_type to user_profile

Revision ID: 741c627fb171
Revises: 7bbf9ff86668
Create Date: 2026-07-13 07:24:53.001528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741c627fb171'
down_revision: Union[str, Sequence[str], None] = '7bbf9ff86668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('goal_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'goal_type')
    # ### end Alembic commands ###