"""initial schema

Revision ID: d226c0736474
Revises: 
Create Date: 2026-07-12 10:41:07.266067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd226c0736474'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() --> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('kcal_target', sa.Numeric(), nullable=False),
    sa.Column('protein_g_target', sa.Numeric(), nullable=False),
    sa.Column('carbs_g_target', sa.Numeric(), nullable=False),
    sa.Column('fat_g_target', sa.Numeric(), nullable=False),
    sa.Column('fiber_g_target', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('kcal_100g', sa.Numeric(), nullable=True),
    sa.Column('protein_100g', sa.Numeric(), nullable=True),
    sa.Column('carbs_100g', sa.Numeric(), nullable=True),
    sa.Column('fat_100g', sa.Numeric(), nullable=True),
    sa.Column('fiber_100g', sa.Numeric(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("origin IN ('manual', 'usda_import', 'ocr_assisted')", name='ck_items_origin'),
    sa.CheckConstraint("type IN ('product', 'ingredient')", name='ck_items_type'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('physiological_guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_value', sa.Numeric(), nullable=True),
    sa.Column('recommended_value', sa.Numeric(), nullable=True),
    sa.Column('max_value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_ingredient_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kcal_100g', sa.Numeric(), nullable=True),
    sa.Column('protein_100g', sa.Numeric(), nullable=True),
    sa.Column('carbs_100g', sa.Numeric(), nullable=True),
    sa.Column('fat_100g', sa.Numeric(), nullable=True),
    sa.Column('fiber_100g', sa.Numeric(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recipe_type', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('servings', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("recipe_type IN ('recipe', 'meal')", name='ck_recipes_type'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Numeric(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('primary_hormone', sa.String(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_goal_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('pct_of_kcal', sa.Numeric(), nullable=False),
    sa.CheckConstraint("meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')", name='ck_meal_goal_splits_meal_type'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'meal_type', name='uq_meal_goal_splits_goal_meal')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'item_id')
    )
    op.create_table('serving_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_g', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('serving_size_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('kcal_logged', sa.Numeric(), nullable=False),
    sa.Column('protein_g_logged', sa.Numeric(), nullable=False),
    sa.Column('carbs_g_logged', sa.Numeric(), nullable=False),
    sa.Column('fat_g_logged', sa.Numeric(), nullable=False),
    sa.Column('fiber_g_logged', sa.Numeric(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')", name='ck_logs_meal_type'),
    sa.CheckConstraint('(item_id IS NOT NULL AND recipe_id IS NULL) OR (item_id IS NULL AND recipe_id IS NOT NULL)', name='ck_logs_item_or_recipe'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['serving_size_id'], ['serving_sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('serving_size_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.CheckConstraint("meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')", name='ck_meal_plans_meal_type'),
    sa.CheckConstraint('(item_id IS NOT NULL AND recipe_id IS NULL) OR (item_id IS NULL AND recipe_id IS NOT NULL)', name='ck_meal_plans_item_or_recipe'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['serving_size_id'], ['serving_sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() --> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plans')
    op.drop_table('logs')
    op.drop_table('serving_sizes')
    op.drop_table('recipe_ingredients')
    op.drop_table('meal_goal_splits')
    op.drop_table('user_profile')
    op.drop_table('recipes')
    op.drop_table('raw_ingredient_reference')
    op.drop_table('physiological_guidelines')
    op.drop_table('items')
    op.drop_table('goals')
    # ### end Alembic commands ###
